@hostname = http://localhost:5000/api

### Get Products
get {{hostname}}/products

### Get Product By Id
get {{hostname}}/products/309530617782993475

### Get Reviews By Product Id
get {{hostname}}/products/309530617782993475/reviews

### Create Product
post {{hostname}}/products
Content-Type: application/json

{
  "name": "The Minimalist Entrepreneur"
}

### Get Reviews
get {{hostname}}/reviews

### Add Review
post {{hostname}}/reviews
Content-Type: application/json

{
  "productId": "309530617782993475",
  "rating": 4,
  "reviewContent": "book was amazing"
}

### Get Single Review
get {{hostname}}/reviews/309478198974874181

### Update Review
put {{hostname}}/reviews/309478198974874181
Content-Type: application/json

{
  "rating": 3,
  "reviewContent": "This review has been updated"
}

### Delete Review
delete {{hostname}}/reviews/309478198974874181
