@hostname = http://localhost:5000/api

### Get Products
get {{hostname}}/products

### Get Product By Id
get {{hostname}}/products/309530617782993475

### Create Product
post {{hostname}}/products
Content-Type: application/json

{
  "name": "The Minimalist Entrepreneur"
}

### Get Reviews
get {{hostname}}/reviews

### Add Review
post {{hostname}}/reviews
Content-Type: application/json

{
  "rating": 5,
  "reviewContent": "This was a good book"
}

### Get Single Review
get {{hostname}}/reviews/309478198974874181

### Update Review
put {{hostname}}/reviews/309478198974874181
Content-Type: application/json

{
  "rating": 3,
  "reviewContent": "This review has been updated"
}

### Delete Review
delete {{hostname}}/reviews/309478198974874181
