@hostname = http://localhost:5000/api

### Get Reviews
get {{hostname}}/reviews

### Add Review
post {{hostname}}/reviews
Content-Type: application/json

{
  "rating": 5,
  "reviewContent": "This was a good book"
}

### Get Single Review
get {{hostname}}/reviews/309478198974874181

### Update Review
put {{hostname}}/reviews/309478198974874181
Content-Type: application/json

{
  "rating": 3,
  "reviewContent": "This review has been updated"
}

### Delete Review
delete {{hostname}}/reviews/309478198974874181
